package kr.codesquad.model.lotto;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class AutoLotto extends Lotto {


    public AutoLotto() {
        this.numbers = makeLotto(generateNumbers());
    }

    @Override
    protected List<Integer> makeLotto(List<Integer> autoGeneratedNumbers) {
        return sortNumbers(autoGeneratedNumbers);
    }

    private List<Integer> generateNumbers() {
        List<Integer> numList = new ArrayList<>();
        for (int num = START_NUMBER; num <= END_NUMBER; num++) {
            numList.add(num);
        }
        Collections.shuffle(numList);
        return numList.subList(0, NUMBER_SIZE);
    }
}
